#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Note:
# Run conventional solver
# Create POD base
# Run PODSolver

runApplication blockMesh
runApplication scalarTransportFoam
runApplication PODSnapshots
runApplication PODSolver
