#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="pimpleDyMIbFoam"

runApplication blockMesh
cp save/boundary constant/polyMesh/

\rm -rf 0
\cp -r 0_org 0

runApplication potentialFoam -writep
runApplication writeIbMasks
runApplication $application
