#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="pimpleDyMFoam"

m4 -P system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh

\sed -i s/empty/symmetryPlane/g constant/polyMesh/boundary
runApplication regionCellSets
runApplication setSet -batch setBatch.batch
runApplication setsToZones -noFlipMap
\cp -r 0_orig 0

# Running is serial
#runApplication $application

# Running in parallel
#decomposePar -cellDist
#mpirun -np 5 pimpleDyMFoam  -parallel
#reconstructPar
