#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

m4 system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication interDyMFoam
