#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=steadyUniversalMRFFoam

#Create the mesh:
m4 < system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
transformPoints -scale "(1 20 1)"
transformPoints -cylToCart "((0 0 0) (0 0 1) (1 0 0))"

# Set 0-directory and create GGI set:
\rm -rf 0
\cp -r save 0
runApplication setSet -batch setBatchGgi
runApplication setsToZones -noFlipMap

runApplication $application
