#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "$caseName: Creating the file blockMeshDict using m4"
m4 -P system/blockMeshDict.m4 > system/blockMeshDict

runApplication blockMesh

runApplication setSet -batch setBatch.batch
runApplication setsToZones -noFlipMap
runApplication potentialFoam
runApplication simpleFoam


