#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

compileApplication ../../setHotRoom

runApplication blockMesh
runApplication setSet -batch setSet.batch
runApplication setsToZones

runApplication setHotRoom
runApplication $application
