#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="steadyCompressibleMRFFoam"

#Create the mesh:
m4 < system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
transformPoints -scale "(1 20 1)"
transformPoints -cylToCart "((0 0 0) (0 0 1) (1 0 0))"

# Set 0-directory and create GGI set:
runApplication setSet -batch setBatchGgi.batch
runApplication setsToZones -noFlipMap

runApplication $application
